# Generated by Django 4.1.7 on 2023-04-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bbsnote", "0004_comment_author_comment_update_date_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-create_date"]},
        ),
    ]
